/* eslint-disable */
// GENERATED - do not edit. Re-run the analyzer's --emit-keys after adding, removing, or
// renaming a definition, or changing an explicit `key`.
//
// The `export {}` is load-bearing: without a top-level import or export this file would be a
// global script, and `declare module` would REPLACE '@reqquest/ui' instead of augmenting it -
// every import from the package would then fail with "has no exported member".
export {}

export type SimplePromptKey =
  | 'id_values_extra_data_prompt'
  | 'id_values_prompt'
  | 'ssn_value_prompt'
  | 'state_residence_confirmation_prompt'
  | 'state_residence_prompt'
  | 'step1_post_residence_prompt'
  | 'step2_post_residence_prompt'
  | 'step3_post_residence_prompt'
  | 'thanks_or_no_thanks_prompt'

export type SimpleRequirementKey =
  | 'id_type_req'
  | 'state_residence_confirmation_req'
  | 'state_residence_req'
  | 'step1_post_residence_req'
  | 'step3_post_residence_req'
  | 'thanks_or_no_thanks_req'

export type SimpleProgramKey =
  | 'adopt_a_pet_program'
  | 'thanks_or_no_thanks_program'

export type DefaultPromptKey =
  | 'applicant_seems_nice_prompt'
  | 'have_a_cat_tower_prompt'
  | 'have_yard_prompt'
  | 'must_exercise_your_dog_prompt'
  | 'not_allergic_to_tuna_prompt'
  | 'other_cats_prompt'
  | 'other_cats_vaccines_prompt'
  | 'vaccine_review_prompt'
  | 'which_state_prompt'

export type DefaultRequirementKey =
  | 'applicant_seems_nice_req'
  | 'have_a_cat_tower_req'
  | 'have_adequate_personal_space_req'
  | 'have_big_yard_req'
  | 'must_exercise_your_dog_req'
  | 'not_allergic_to_tuna_req'
  | 'other_cats_applicant_req'
  | 'other_cats_reviewer_req'
  | 'which_state_req'

export type DefaultProgramKey =
  | 'adopt_a_cat_program'
  | 'adopt_a_dog_program'

export type ComplexPromptKey =
  | 'accept_cat_prompt'
  | 'accept_dog_prompt'
  | 'accept_foster_pet_prompt'
  | 'approve_reviewer_exercise_exemption_prompt'
  | 'bridge_of_death_prompt'
  | 'children_prompt'
  | 'confirm_cat_microchip_service_prompt'
  | 'current_catowner_prompt'
  | 'current_dogowner_prompt'
  | 'dog_exercise_prompt'
  | 'living_space_prompt'
  | 'owner_cat_allergy_prompt'
  | 'owner_cat_microchip_service_prompt'
  | 'owner_dog_allergy_prompt'
  | 'petowner_prompt'
  | 'previous_catowner_prompt'
  | 'previous_dog_surrender_foster_prompt'
  | 'previous_dog_surrender_prompt'
  | 'previous_dogowner_prompt'
  | 'review_applicant_cat_info_prompt'
  | 'review_applicant_dog_info_prompt'
  | 'review_applicant_foster_a_pet_info_prompt'
  | 'review_applicant_state_residence_info_prompt'
  | 'review_movie_lover_answers_prompt'
  | 'state_residence_prompt'
  | 'terms_and_conditions_prompt'
  | 'yard_prompt'

export type ComplexRequirementKey =
  | 'accept_adopt_cat_req'
  | 'accept_adopt_dog_req'
  | 'accept_fost_pet_req'
  | 'approve_reviewer_exercise_exemption_workflow_req'
  | 'children_qual_req'
  | 'confirm_cat_microchip_service_workflow_req'
  | 'current_catowner_qual_req'
  | 'current_dogowner_qual_req'
  | 'dog_exercise_qual_req'
  | 'living_space_qual_req'
  | 'movie_lover_qual_req'
  | 'owner_cat_allergy_qual_req'
  | 'owner_cat_microchip_service_qual_req'
  | 'owner_dog_allergy_qual_req'
  | 'petowner_prequal_req'
  | 'previous_catowner_qual_req'
  | 'previous_dog_surrender_foster_qual_req'
  | 'previous_dog_surrender_qual_req'
  | 'previous_dogowner_qual_req'
  | 'review_applicant_cat_info_app_req'
  | 'review_applicant_dog_info_app_req'
  | 'review_applicant_foster_a_pet_info_app_req'
  | 'review_applicant_state_residence_app_req'
  | 'review_movie_lover_app_req'
  | 'state_residence_prequal_req'
  | 'terms_and_conditions_post_qual_req'
  | 'yard_qual_req'

export type ComplexProgramKey =
  | 'adopt_a_cat_program'
  | 'adopt_a_dog_program'
  | 'foster_a_pet_program'

export type RcPromptKey =
  | 'application_management_opt_out_prompt'
  | 'assess_attention_detail_prompt'
  | 'assess_communication_prompt'
  | 'assess_critical_thinking_prompt'
  | 'assess_data_related_puzzle_prompt'
  | 'assess_maintain_sys_documentation_prompt'
  | 'assess_organization_prompt'
  | 'assess_outside_class_example_prompt'
  | 'assess_reccomendation_letter_prompt'
  | 'assess_support_communication_prompt'
  | 'assess_technical_troubleshooting_prompt'
  | 'audit_software_development_non_blocking_show_regular_prompt'
  | 'audit_software_development_non_blocking_show_regular_prompt2'
  | 'audit_software_development_non_blocking_show_submitted_prompt'
  | 'audit_software_development_non_blocking_show_submitted_prompt2'
  | 'communication_prompt'
  | 'critical_thinking_prompt'
  | 'data_related_puzzle_prompt'
  | 'evidence_automation_prompt'
  | 'investigated_future_career_prompt'
  | 'maintain_sys_documentation_prompt'
  | 'operations_infrastructure_opt_out_prompt'
  | 'organization_prompt'
  | 'outside_class_example_prompt'
  | 'pre_qual_prompt'
  | 'pre_qual_user_info_prompt'
  | 'project_management_opt_out_prompt'
  | 'rate_future_career_prompt'
  | 'reccomendation_letter_prompt'
  | 'reviewer_override_gpa_warning_prompt'
  | 'reviewer_software_development_second_eyes_prompt'
  | 'software_dev_opt_out_prompt'
  | 'support_communication_prompt'
  | 'technical_troubleshooting_prompt'
  | 'written_automation_prompt'

export type RcRequirementKey =
  | 'application_management_opt_out_req'
  | 'assess_attention_detail_req'
  | 'assess_communicationn_req'
  | 'assess_critical_thinking_req'
  | 'assess_data_related_puzzle_req'
  | 'assess_maintain_sys_documentation_req'
  | 'assess_organization_req'
  | 'assess_outside_class_example_req'
  | 'assess_reccomendation_lettern_req'
  | 'assess_support_communicationn_req'
  | 'assess_technical_troubleshootingn_req'
  | 'audit_software_development_non_blocking_show_regular_req'
  | 'audit_software_development_non_blocking_show_regular_req2'
  | 'audit_software_development_non_blocking_show_submitted_req'
  | 'audit_software_development_non_blocking_show_submitted_req2'
  | 'communication_req'
  | 'critical_thinking_req'
  | 'data_related_puzzle_req'
  | 'evidence_automation_req'
  | 'investigated_future_career_req'
  | 'maintain_sys_documentation_req'
  | 'operations_infrastructure_opt_out_req'
  | 'organization_req'
  | 'outside_class_example_req'
  | 'project_management_opt_out_req'
  | 'rate_future_career_req'
  | 'reccomendation_letter_req'
  | 'reviewer_override_gpa_warning_req'
  | 'reviewer_software_development_second_eyes_req'
  | 'software_dev_opt_out_req'
  | 'step1_prequal_req'
  | 'support_communication_req'
  | 'technical_troubleshooting_req'
  | 'written_automation_req'

export type RcProgramKey =
  | 'application_management_support'
  | 'operations_infrastructure'
  | 'project_management'
  | 'software_development'

declare module '@reqquest/ui' {
  interface ReqQuestKeys {
    prompts:
      | 'accept_cat_prompt'
      | 'accept_dog_prompt'
      | 'accept_foster_pet_prompt'
      | 'applicant_seems_nice_prompt'
      | 'application_management_opt_out_prompt'
      | 'approve_reviewer_exercise_exemption_prompt'
      | 'assess_attention_detail_prompt'
      | 'assess_communication_prompt'
      | 'assess_critical_thinking_prompt'
      | 'assess_data_related_puzzle_prompt'
      | 'assess_maintain_sys_documentation_prompt'
      | 'assess_organization_prompt'
      | 'assess_outside_class_example_prompt'
      | 'assess_reccomendation_letter_prompt'
      | 'assess_support_communication_prompt'
      | 'assess_technical_troubleshooting_prompt'
      | 'audit_software_development_non_blocking_show_regular_prompt'
      | 'audit_software_development_non_blocking_show_regular_prompt2'
      | 'audit_software_development_non_blocking_show_submitted_prompt'
      | 'audit_software_development_non_blocking_show_submitted_prompt2'
      | 'bridge_of_death_prompt'
      | 'children_prompt'
      | 'communication_prompt'
      | 'confirm_cat_microchip_service_prompt'
      | 'critical_thinking_prompt'
      | 'current_catowner_prompt'
      | 'current_dogowner_prompt'
      | 'data_related_puzzle_prompt'
      | 'dog_exercise_prompt'
      | 'evidence_automation_prompt'
      | 'have_a_cat_tower_prompt'
      | 'have_yard_prompt'
      | 'id_values_extra_data_prompt'
      | 'id_values_prompt'
      | 'investigated_future_career_prompt'
      | 'living_space_prompt'
      | 'maintain_sys_documentation_prompt'
      | 'must_exercise_your_dog_prompt'
      | 'not_allergic_to_tuna_prompt'
      | 'operations_infrastructure_opt_out_prompt'
      | 'organization_prompt'
      | 'other_cats_prompt'
      | 'other_cats_vaccines_prompt'
      | 'outside_class_example_prompt'
      | 'owner_cat_allergy_prompt'
      | 'owner_cat_microchip_service_prompt'
      | 'owner_dog_allergy_prompt'
      | 'petowner_prompt'
      | 'pre_qual_prompt'
      | 'pre_qual_user_info_prompt'
      | 'previous_catowner_prompt'
      | 'previous_dog_surrender_foster_prompt'
      | 'previous_dog_surrender_prompt'
      | 'previous_dogowner_prompt'
      | 'project_management_opt_out_prompt'
      | 'rate_future_career_prompt'
      | 'reccomendation_letter_prompt'
      | 'review_applicant_cat_info_prompt'
      | 'review_applicant_dog_info_prompt'
      | 'review_applicant_foster_a_pet_info_prompt'
      | 'review_applicant_state_residence_info_prompt'
      | 'review_movie_lover_answers_prompt'
      | 'reviewer_override_gpa_warning_prompt'
      | 'reviewer_software_development_second_eyes_prompt'
      | 'software_dev_opt_out_prompt'
      | 'ssn_value_prompt'
      | 'state_residence_confirmation_prompt'
      | 'state_residence_prompt'
      | 'step1_post_residence_prompt'
      | 'step2_post_residence_prompt'
      | 'step3_post_residence_prompt'
      | 'support_communication_prompt'
      | 'technical_troubleshooting_prompt'
      | 'terms_and_conditions_prompt'
      | 'thanks_or_no_thanks_prompt'
      | 'vaccine_review_prompt'
      | 'which_state_prompt'
      | 'written_automation_prompt'
      | 'yard_prompt'
    requirements:
      | 'accept_adopt_cat_req'
      | 'accept_adopt_dog_req'
      | 'accept_fost_pet_req'
      | 'applicant_seems_nice_req'
      | 'application_management_opt_out_req'
      | 'approve_reviewer_exercise_exemption_workflow_req'
      | 'assess_attention_detail_req'
      | 'assess_communicationn_req'
      | 'assess_critical_thinking_req'
      | 'assess_data_related_puzzle_req'
      | 'assess_maintain_sys_documentation_req'
      | 'assess_organization_req'
      | 'assess_outside_class_example_req'
      | 'assess_reccomendation_lettern_req'
      | 'assess_support_communicationn_req'
      | 'assess_technical_troubleshootingn_req'
      | 'audit_software_development_non_blocking_show_regular_req'
      | 'audit_software_development_non_blocking_show_regular_req2'
      | 'audit_software_development_non_blocking_show_submitted_req'
      | 'audit_software_development_non_blocking_show_submitted_req2'
      | 'children_qual_req'
      | 'communication_req'
      | 'confirm_cat_microchip_service_workflow_req'
      | 'critical_thinking_req'
      | 'current_catowner_qual_req'
      | 'current_dogowner_qual_req'
      | 'data_related_puzzle_req'
      | 'dog_exercise_qual_req'
      | 'evidence_automation_req'
      | 'have_a_cat_tower_req'
      | 'have_adequate_personal_space_req'
      | 'have_big_yard_req'
      | 'id_type_req'
      | 'investigated_future_career_req'
      | 'living_space_qual_req'
      | 'maintain_sys_documentation_req'
      | 'movie_lover_qual_req'
      | 'must_exercise_your_dog_req'
      | 'not_allergic_to_tuna_req'
      | 'operations_infrastructure_opt_out_req'
      | 'organization_req'
      | 'other_cats_applicant_req'
      | 'other_cats_reviewer_req'
      | 'outside_class_example_req'
      | 'owner_cat_allergy_qual_req'
      | 'owner_cat_microchip_service_qual_req'
      | 'owner_dog_allergy_qual_req'
      | 'petowner_prequal_req'
      | 'previous_catowner_qual_req'
      | 'previous_dog_surrender_foster_qual_req'
      | 'previous_dog_surrender_qual_req'
      | 'previous_dogowner_qual_req'
      | 'project_management_opt_out_req'
      | 'rate_future_career_req'
      | 'reccomendation_letter_req'
      | 'review_applicant_cat_info_app_req'
      | 'review_applicant_dog_info_app_req'
      | 'review_applicant_foster_a_pet_info_app_req'
      | 'review_applicant_state_residence_app_req'
      | 'review_movie_lover_app_req'
      | 'reviewer_override_gpa_warning_req'
      | 'reviewer_software_development_second_eyes_req'
      | 'software_dev_opt_out_req'
      | 'state_residence_confirmation_req'
      | 'state_residence_prequal_req'
      | 'state_residence_req'
      | 'step1_post_residence_req'
      | 'step1_prequal_req'
      | 'step3_post_residence_req'
      | 'support_communication_req'
      | 'technical_troubleshooting_req'
      | 'terms_and_conditions_post_qual_req'
      | 'thanks_or_no_thanks_req'
      | 'which_state_req'
      | 'written_automation_req'
      | 'yard_qual_req'
    programs:
      | 'adopt_a_cat_program'
      | 'adopt_a_dog_program'
      | 'adopt_a_pet_program'
      | 'application_management_support'
      | 'foster_a_pet_program'
      | 'operations_infrastructure'
      | 'project_management'
      | 'software_development'
      | 'thanks_or_no_thanks_program'
  }
}
