services:
  api:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: ${API_INSTANCE:-testserver}/Dockerfile.dev
    ports:
      - 127.0.0.1:81:80
      - 127.0.0.1:9229:9229
    environment:
      TZ: America/Chicago
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_DATABASE: default_database
      MYSQL_USER: user
      MYSQL_PASS: password
      JWT_TRUSTED_ISSUERS: '[{ "iss": "unified-auth", "url": "http://fakeauth/jwks" }, { "iss": "reqquest", "secret": "reqquest" }]'
      RESET_DB_ON_STARTUP: 'true'
    volumes:
      - ./api/src:/usr/app/api/src
      - ./api/dist:/usr/app/api/dist
      - ./${API_INSTANCE:-testserver}/src:/usr/app/${API_INSTANCE:-testserver}/src
  ui:
    build:
      context: .
      dockerfile: ${UI_INSTANCE:-ui}/Dockerfile.dev
    ports:
      - 127.0.0.1:80:80
    environment:
      PUBLIC_API_BASE: http://localhost:81
      PUBLIC_AUTH_REDIRECT: http://localhost:3001/login?clientId=reqquest&returnUrl=http%3A%2F%2Flocalhost
      PUBLIC_ENVIRONMENT: 'DEV'
    volumes:
      - ./${UI_INSTANCE:-ui}/src:/usr/app/src
      - ./ui/.svelte-kit/types:/usr/app/.svelte-kit/types
      - ./ui/svelte.config.js:/usr/app/svelte.config.js
      - ./ui/vite.config.ts:/usr/app/vite.config.ts
  fakeauth:
    image: registry.its.txstate.edu/unified-auth-stub:dev
    attach: false
    ports:
      - 127.0.0.1:3001:80
  mysql:
    image: percona/percona-server:8.4
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: default_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    attach: false
    healthcheck:
      test: ["CMD", "sh", "/healthcheck.sh"]
      interval: 1s
      timeout: 0.5s
      retries: 50
    volumes:
      - ./healthcheck.sh:/healthcheck.sh
      - reqquestdb:/var/lib/mysql
volumes:
  reqquestdb: {}
