FROM node:24-alpine
WORKDIR /usr/app/api
COPY api/package.json api/package-lock.json ./
RUN npm ci
COPY api/tsconfig.json ./
COPY api/src src
WORKDIR /usr/app/demos
COPY demos/package.json ./
COPY demos/package-lock.json ./
RUN npm ci
COPY demos/tsconfig.json ./
COPY demos/src src
RUN mkdir -p /files
RUN mkdir -p /files/tmp
RUN mkdir -p /files/storage

CMD [ "npm", "run", "start:nodemon" ]
