FROM node:24-alpine
WORKDIR /usr/app/api
COPY api/package.json api/package-lock.json ./
RUN npm ci
COPY api/tsconfig.json ./
COPY api/src src
WORKDIR /usr/app/demos/simple/api
COPY demos/simple/api/package.json ./
COPY demos/simple/api/package-lock.json ./
RUN npm i
COPY demos/simple/api/tsconfig.json ./
COPY demos/simple/api/src src

CMD [ "npm", "run", "start:nodemon" ]
