FROM node:24-alpine

WORKDIR /usr/app
COPY ui/package.json ./
COPY ui/package-lock.json ./
COPY ui/svelte.config.js ./
COPY ui/tailwind.config.js ./
COPY ui/postcss.config.js ./
COPY ui/tsconfig.json ./
COPY ui/vite.config.ts ./
RUN npm ci
COPY ui/src src
COPY ui/static static

CMD ["npm", "run", "dev"]
